#!/bin/bash

# To install, copy this file into /usr/bin/

if [ -z ${1+x} ]; then
	echo
	echo "ERROR: Expected a {USERNAME}@{SERVER}"
	echo
	echo "Usage: ${0} user@192.168.1.1"
	echo
	exit
fi
IP=$(echo $1 | awk -F'@' '{print $NF}')
nc -z -w 5 ${IP} 22 &> /dev/null
if [ $? -eq 0 ]; then
	cat ~/.ssh/id_rsa.pub | ssh ${1}  "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"
	ssh ${1}
else
	echo "The SSH port on ${IP} is not currently reachable"
fi
